- name: install haproxy
  yum:
    name: haproxy
    state: present

- name: Create haproxy directories
  file: 
    dest: /etc/{{ item }} 
    state: directory
  with_items:
    - haproxy
    - haproxy/errors  
  tags: haproxy

- name: create errors files
  file: 
    path: /etc/haproxy/errors/{{ item }}.http 
    owner: root
    group: root
    mode: 0655 
    state: touch
  with_items:
    - 400
    - 403
    - 408
    - 500
    - 502
    - 503
    - 504       

- name: Copy haproxy config
  block:
  - template: 
      src: /srv/git/ansible_{{ location }}_localisations/templates/haproxy/haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    when: localised_haproxy_config == true   
  - template: 
      src: templates/haproxy.cfg.j2 
      dest: /etc/haproxy/haproxy.cfg
    when: localised_haproxy_config == false
    notify:  
      - restart haproxy    
  tags: 
    - haproxy